Device name consistency
ajcasagrande/device-onvif-camera pull request #10
Opened 2022-07-15 22:31 UTC by presatish

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2022-07-15 23:17 UTC, ChristianDarr-personal requested changes
Looks good to me, I made a few suggestions

2022-07-15 23:17 UTC, ChristianDarr-personal commented on internal/driver/getsetfriendlyname.go
> +	}
```suggestion
	var dataObj string
	err := json.Unmarshal(data, &dataObj)
	if err != nil {
		return device, errors.NewCommonEdgeX(errors.KindServerError, "failed to unmarshal the json request body", err)
	}
	if len(dataObj) == 0 {
		return device, errors.NewCommonEdgeX(errors.KindContractInvalid, "no data in request body", err)
	}

	device.Protocols[OnvifProtocol][FriendlyName] = dataObj // create or update friendly name field

	return device, nil
```

2022-07-15 23:17 UTC, ChristianDarr-personal commented on internal/driver/getsetfriendlyname.go
> +	}
I would recommend doing something like this, for both mac and friendly name, so that the input json only takes in data like this:
`{
"FriendlyName": {
        "Home Camera"
}
}
`
Which will allow for less user error

2022-07-15 23:17 UTC, ChristianDarr-personal commented on internal/driver/getsetmac.go
> +func (onvifClient *OnvifClient) setMACAddress(device contract.Device, data []byte) (contract.Device, errors.EdgeX) {
Same comment about only taking in a single string as opposed to a key value pair

2022-07-18 15:18 UTC, presatish commented on internal/driver/getsetfriendlyname.go
> +	}
I considered this while implementing the story but it is not as simple as this. We need to change `object` to `string` in profiles and the current `HandleReadCommands()` takes in only Object value. It did seem like some fair amount of refactoring was needed. Had a discussion with @ajcasagrande too and we decided to keep it this way for now given the time constraints.

2022-07-18 15:42 UTC, ChristianDarr-personal commented on internal/driver/getsetfriendlyname.go
> +	}
That makes sense, I didn't know some of the other constraints.

2022-07-18 18:08 UTC, ajcasagrande requested changes

2022-07-18 18:08 UTC, ajcasagrande commented on internal/driver/onvifclient.go
> +	case SetFriendlyName:
there is a lot of duplicated boiler plate code in here that should probably be cleaned up later.

2022-07-19 16:04 UTC, ChristianDarr-personal approved these changes

2022-07-19 16:04 UTC, ChristianDarr-personal commented on doc/get-set-friendlyname-mac.md
> +curl http://localhost:59882/api/v2/device/name/<device name>/FriendlyName | json_pp
I think we are changing all of these to `jq` instead of `json_pp`

2022-07-19 19:09 UTC, ajcasagrande commented on doc/get-set-friendlyname-mac.md
> +curl http://localhost:59882/api/v2/device/name/<device name>/FriendlyName | json_pp
ok that is what I was going to suggest as well, but wasn't sure if that is where the other documentation was going. @presatish for safety use `| jq .` as not all version of `jq` support being called without the `.` param (which is a select all).

2022-07-19 23:03 UTC, ajcasagrande approved these changes

2022-07-19 23:03 UTC, merged