feat: Endpointref
ajcasagrande/device-onvif-camera pull request #11
Opened 2022-07-18 15:53 UTC by brianointel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

added a unit test to check for noauth path; return noauth path when mac is invalid

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2022-07-18 21:19 UTC, ajcasagrande requested changes

2022-07-18 22:03 UTC, ChristianDarr-personal approved these changes
LGTM

2022-07-19 00:38 UTC, ajcasagrande commented on internal/driver/credentials_test.go
> +// TestTryGetCredentials verifies when a credential is passed with a noAuth path, noAuth credentials are returned.
Fix function name in comment

2022-07-19 00:39 UTC, ajcasagrande requested changes
Last thing

2022-07-19 16:18 UTC, ajcasagrande approved these changes
LGTM

2022-07-19 16:20 UTC, merged