Discovery probe
ajcasagrande/device-onvif-camera pull request #3
Opened 2022-05-11 18:58 UTC by ChristianDarr-personal

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2022-05-16 18:55 UTC, brianointel approved these changes

2022-05-17 03:43 UTC, ajcasagrande requested changes

2022-05-17 03:43 UTC, ajcasagrande commented on cmd/res/configuration.toml
> +# Allows the option for different discovery mechanisms
```suggestion
# Select which discovery mechanism(s) to use
```

2022-05-17 03:43 UTC, ajcasagrande commented on cmd/res/configuration.toml
>  # List of IPv4 subnets to perform LLRP discovery process on, in CIDR format (X.X.X.X/Y)
LLRP should be removed

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery-docker.md
> +However, we can’t send the multicast message from the **edgex network** to the **host network** in the **docker container**.
Actually a lot of this section is just plain incorrect now and should be removed/re-written as we do not plan on the user using host-mode networking.

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery-docker.md
> +      SERVICE_HOST: 192.168.0.0
not sure if this should be changed?

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery-docker.md
> +The user can use docker logs to trace the auto-discovery
By default the log level is INFO, but the logs you show here are DEBUG

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery.md
> +There are two methods that the device service can use to discover and add ONVIF compliant cameras, WS-Discovery and netscan.
I think technically the netscan is still ws-discovery, just using unicast instead of multicast

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery.md
> +    > The Hello message from HIKVISION
isn't this the tapo one?

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery.md
> + This method is going to be slower than WS-Discovery, becuase it has to make individual connections. However, it can reach a much wider net of networks and devices than WS-Discovery.
`set of networks`?

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery.md
> +DiscoveryEthernetInterface = "" # The target EthernetInterface for discovery. Defaults to 'en0'
```suggestion
DiscoveryEthernetInterface = "" # The target EthernetInterface for discovery.
```

2022-05-17 03:43 UTC, ajcasagrande commented on doc/auto-discovery.md
> +Device discovery is triggered by the device SDK. Once the device service starts, it will discover the Onvif camera(s) within the specified interval.
it is not `within`, but maybe `at`? Also device discovery can be triggered via a POST call as well. `curl -X POST http://127.0.0.1:59984/api/v2/discovery` (double check that url)

2022-05-17 03:43 UTC, ajcasagrande commented on doc/docker-compose/add-device-onvif-camera.yml
> -      - "127.0.0.1:59984:59984"
this should not be removed

2022-05-17 03:43 UTC, ajcasagrande commented on doc/docker-compose/add-device-onvif-camera.yml
> +      SERVICE_HOST: edgex-device-onvif-camera # replace with system IP
This comment is wrong

2022-05-17 03:43 UTC, ajcasagrande commented on doc/docker-compose/add-device-onvif-camera.yml
> +      DRIVER_DEFAULTSECRETPATH: credentials001
I think these should be removed

2022-05-17 03:43 UTC, ajcasagrande commented on doc/docker-compose/add-device-onvif-camera.yml
> +    command: -cp=consul.http://localhost:8500 --registry --confdir=/res
not sure if this is needed, plus the url should not be localhost

2022-05-17 16:54 UTC, ChristianDarr-personal commented on doc/docker-compose/add-device-onvif-camera.yml
> +      SERVICE_HOST: edgex-device-onvif-camera # replace with system IP
Whenever I try to run this with `SERVICE_HOST` set to edgex-device-onvif-camera, it loses connection with the device service shortly after discovery. It works if I use my local IP

2022-05-17 17:45 UTC, ChristianDarr-personal commented on doc/auto-discovery-docker.md
> +The user can use docker logs to trace the auto-discovery
I think I have the loglevel set to debug in the example, but I can change it to match and generate new output

2022-05-17 22:14 UTC, ajcasagrande requested changes

2022-05-17 22:14 UTC, ajcasagrande commented on doc/docker-compose/add-device-onvif-camera.yml
> +
there is something funky with this last line. it shows as no new-line, however it also shows a blank line. maybe its not blank?

2022-05-17 22:14 UTC, ajcasagrande commented on doc/auto-discovery.md
> +DiscoverySubnets = ""
update this section to match the changed toml file

2022-05-17 22:14 UTC, ajcasagrande commented on doc/auto-discovery.md
> + This method is going to be slower than WS-Discovery, becuase it has to make individual connections. However, it can reach a much wider Set of networks and devices than WS-Discovery.
```suggestion
This method is going to be slower and more network-intensive than multicast WS-Discovery, becuase it has to make individual connections. However, it can reach a much wider set of networks and works better behind NATs (such as docker networks).
```

2022-05-17 22:14 UTC, ajcasagrande commented on cmd/res/configuration.toml
> +
if there is 2 blank lines here, just make it 1

2022-05-17 22:26 UTC, ajcasagrande approved these changes
LGTM

2022-05-17 22:28 UTC, merged