Discovery probe
ajcasagrande/device-onvif-camera pull request #4
Opened 2022-05-13 16:48 UTC by brianointel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?
Alternate method for discovering cameras

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2022-05-13 21:25 UTC, ChristianDarr-personal reviewed
I don't know what priority this is, but I was trying to run this with 300 instances of the emulator up and running, and no matter how I changed the configuration, netscan inconsistently discovered the devices, discovering anywhere from 228/300 to 300/300. I haven't figured out exactly what the issue is yet, and I plan on trying more configurations.

2022-05-16 17:35 UTC, presatish requested changes
Most of it looks good, posted some comments and conflicts need to be resolved.

2022-05-16 17:35 UTC, presatish commented on cmd/res/configuration.toml
> +# List of IPv4 subnets to perform LLRP discovery process on, in CIDR format (X.X.X.X/Y)
Typo `LLRP` needs to be removed

2022-05-16 17:35 UTC, presatish commented on internal/driver/driver.go
> +
This extra line is not needed, can be grouped with other edgex dependencies.

2022-05-16 17:35 UTC, presatish commented on internal/driver/driver.go
> +			return nil, errors.NewCommonEdgeX(errors.KindServerError, fmt.Sprintf("failed to initial onvif client for '%s' camera", dev.Name), err)
Same comment as above `initialize` instead of `initial`

2022-05-16 17:35 UTC, presatish commented on internal/driver/driver.go
>  // createOnvifClient create the Onvif client for specified the device
This comment needs to be modified a bit.

2022-05-16 17:35 UTC, presatish commented on internal/driver/driver.go
> +		return errors.NewCommonEdgeX(errors.KindServerError, fmt.Sprintf("failed to initial onvif client for '%s' camera", dev.Name), err)
`initialize` instead of `initial`.

2022-05-16 17:38 UTC, brianointel reviewed
looks good!

2022-05-16 18:30 UTC, presatish commented on cmd/discover/main.go
> +package main
So I see there are two main.go files. Are both needed?

2022-05-16 18:31 UTC, presatish commented on cmd/discover/main.go
> +func SendUDPUnicast(msg string, ip net.IP) []string {
Is this method needed, seems like it is not used?

2022-05-16 19:38 UTC, presatish commented on internal/driver/service.go
> +// Copyright (C) 2020 Intel Corporation
`2022` instead of `2020`

2022-05-16 19:38 UTC, presatish commented on internal/driver/service_test.go
> +// Copyright (C) 2020 Intel Corporation
Same as above

2022-05-16 19:39 UTC, presatish commented on internal/driver/service_test.go
> +			ProfileName: "LLRP-Device-Profile",
Profile needs to be updated.

2022-05-17 03:20 UTC, ajcasagrande requested changes
A few comments

2022-05-17 03:20 UTC, ajcasagrande commented on internal/driver/driver.go
> +	d.lc.Info(fmt.Sprintf("Discovered %d device(s) in %v via netscan.", len(result), time.Since(t1)))
Use d.lc.Infof without fmt.Sprintf

2022-05-17 03:20 UTC, ajcasagrande commented on internal/driver/driver.go
> +			d.lc.Warnf("unable to cast res.Data into sdkModel.DiscoveredDevice. type=%T", res.Info)
should be changed to `res.Info` now

2022-05-17 03:20 UTC, ajcasagrande commented on internal/driver/driver.go
> +func (d *Driver) discoverNetcast(ctx context.Context, discovered []sdkModel.DiscoveredDevice) []sdkModel.DiscoveredDevice {
it is already sort-of handled by the netscan code, but we may want to short-circuit this code if the subnets is blank, so that way you don't see "Discovered 0 device(s) in 0.159 nanoseconds"

2022-05-17 03:20 UTC, ajcasagrande commented on internal/driver/service.go
> +	// but the metadata service API for opstate updates changed between v1.1.0 and v1.2.0.
This may be invalid given we are using 2.x now. Right now the function isn't being used that I know of, so maybe get rid of it for now.

2022-05-17 03:20 UTC, ajcasagrande commented on pkg/netscan/util.go
> +package netscan
I think there might be some existing unit tests we can bring over from LLRP service

2022-05-17 03:20 UTC, ajcasagrande commented on pkg/netscan/discover.go
> +// ipWorker pulls uint32s from the ipCh, convert to IPs, filters then ip
? not sure what my original wording meant to say
```suggestion
// ipWorker pulls uint32s from the ipCh, convert to IPs, filters them
```

2022-05-17 16:48 UTC, brianointel commented on internal/driver/driver.go
> +	Both            = "both"
I made them an enum but kept them as capitalized. let me know if you want that changed

2022-05-17 17:09 UTC, presatish commented on internal/driver/driver.go
> +
Pretty sure go fmt/IDE does not complain about an extra line in the import statements but extra line here should be fine as this is an internal dependency which I didn't notice before.

2022-05-17 17:44 UTC, presatish commented
Also change the log messages from `Trace` to `Debug`, @ajcasagrande said `Trace` was added just for testing purposes.

2022-05-17 17:46 UTC, ajcasagrande commented
> Also change the log messages from `Trace` to `Debug`, @ajcasagrande said `Trace` was added just for testing purposes.

Actually it should always be set to `INFO` and only changed to `DEBUG` or `TRACE` by user overrides (consul or env).

2022-05-17 18:00 UTC, presatish commented on cmd/discover/main.go
> +package main
Please add a comment/explanation on this file to explain why and when its needed.

2022-05-17 22:22 UTC, ajcasagrande commented on pkg/netscan/util.go
> +package netscan
done

2022-05-17 23:01 UTC, brianointel commented on internal/driver/service.go
> +	// but the metadata service API for opstate updates changed between v1.1.0 and v1.2.0.
seems to be needed for the sdk

2022-05-17 23:39 UTC, ajcasagrande commented
> I don't know what priority this is, but I was trying to run this with 300 instances of the emulator up and running, and no matter how I changed the configuration, netscan inconsistently discovered the devices, discovering anywhere from 228/300 to 300/300. I haven't figured out exactly what the issue is yet, and I plan on trying more configurations.

This may just be a factor of how many responses it is sending over a single connection. I would suggest upping the `ProbeTimeoutMillis` and seeing if that fixes it.

2022-05-17 23:43 UTC, ajcasagrande commented on internal/driver/driver.go
> +	d.lc.Info(fmt.Sprintf("Discovered %d device(s) in %v via multicast.", len(onvifDevices), time.Since(t0)))
```suggestion
	d.lc.Infof("Discovered %d device(s) in %v via multicast.", len(onvifDevices), time.Since(t0)))
```

2022-05-17 23:43 UTC, ajcasagrande commented on internal/driver/driver.go
> +			d.lc.Info("unable to cast res.Data into sdkModel.DiscoveredDevice. type=%T", res.Info)
```suggestion
			d.lc.Warnf("unable to cast res.Info into sdkModel.DiscoveredDevice. type=%T", res.Info)
```

2022-05-17 23:43 UTC, ajcasagrande commented on internal/driver/service.go
> +	// but the metadata service API for opstate updates changed between v1.1.0 and v1.2.0.
no, it is just a required part of the interface we created, it is safe to remove.

2022-05-18 00:05 UTC, ajcasagrande approved these changes
LGTM

2022-05-18 00:05 UTC, closed without merging