Rediscovery
ajcasagrande/device-onvif-camera pull request #5
Opened 2022-05-26 20:05 UTC by ChristianDarr-personal

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?
There is now a filter to avoid adding duplicates into core metadata, based on Endpoint Reference Address. It will also update the network address if necessary.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?
No.
## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2022-05-27 19:13 UTC, ajcasagrande commented on internal/driver/onvifdiscovery.go
> +// // checkConnection compares all existing devices and searches for a matching discovered device
Is this code for an upcoming PR?

2022-05-27 19:13 UTC, ajcasagrande commented on internal/driver/onvifdiscovery.go
> +}
```suggestion
func (d *Driver) discoverFilter(discoveredDevices []sdkModel.DiscoveredDevice) (filtered []sdkModel.DiscoveredDevice) {
	// filter out duplicate discovered devices by endpoint reference
	discoveredMap := make(map[string]sdkModel.DiscoveredDevice)
	for _, device := range discoveredDevices {
		endpointRef := device.Protocols[OnvifProtocol][EndpointRefAddress]
		if _, found := discoveredMap[endpointRef]; !found {
			discoveredMap[endpointRef] = device
		}
	}

	existingDevices := d.makeDeviceMap() // create comparison map

	// loop through discovered devices and see if they are already discovered
	for endpointRef, device := range discoveredMap {
		if existingDevice, found := existingDevices[endpointRef]; found {
			if err := d.updateExistingDevice(existingDevice, device); err != nil {
				d.lc.Errorf("error occurred while updating existing device %s: %s", existingDevice.Name, err.Error())
			}
			continue // skip registering existing device
		}
		// if device was not found, add it to the list of new devices to be registered with EdgeX
		filtered = append(filtered, device)
	}

	return filtered
}
```

2022-05-27 19:26 UTC, ChristianDarr-personal commented on internal/driver/onvifdiscovery.go
> +// // checkConnection compares all existing devices and searches for a matching discovered device
This would apply to "2448: determine onvif cameras that used to be discoverable and are no longer discovered (last seen)"
Is there a big enough difference between discoverability vs. device status to warrant this function, or a similar function to run during discovery? Otherwise this other code should do the same thing

2022-06-02 19:15 UTC, ajcasagrande requested changes
Looks good for a first pass.

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +		}
after looking more into the code, i think it actually might make more sense to use a big if, else if, else if, else block, and then store a temp variable for the status and only send the status in one place. psuedocode:

```
status := Unreachable
if testConnectionAuth { 
   status = UpWithAuth
} else if testConnectionNoAuth {
   status = UpWithNoAuth
} ... {
  ...
}

if err := d.updateDeviceStatus(device, status); err != nil {
	d.lc.Warnf("Could not update device status for device %s: %s", device.Name, err.Error())
}
```

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +		d.lc.Debugf("Connection to %s failed when using authentication", device.Name)
should the edgexErr be logged here, or is it already?

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	port := device.Protocols[OnvifProtocol][Port]
I think you should ensure they exist (i think makeDeviceMap does something similar?)

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	_, err := http.Get(host)
i think this should be using a raw `net.DialWithTimeout` over TCP or ICMP probe

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	if seen {
can just use `status != Unreachable`

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	device.Protocols[OnvifProtocol][DeviceStatusDescription] = desc
like i said, i don't see the point in this

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +		device.Protocols[OnvifProtocol][LastSeen] = time.Now().Format(time.UnixDate)
not sure what format this is, but I think typically we just use like `time.Now().UnixNano()` or something like that.

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	return nil
just return the response directly
```suggestion
	return service.RunningService().UpdateDevice(device)
```

2022-06-02 19:15 UTC, ajcasagrande commented on internal/driver/driver.go
> +func (d *Driver) updateExistingDevice(device models.Device, discDev sdkModel.DiscoveredDevice) error {
does this integrate some of the changes I requested in your first PR?

2022-06-02 19:40 UTC, ChristianDarr-personal commented on internal/driver/constants.go
> +	Unreachable   = "Unreachable"
I wanted to do that and tried it, but if we want to store it in the the device.Protocols map, it will only accept strings. Should I still do that and cast the value to a string?

2022-06-02 20:48 UTC, ChristianDarr-personal commented on internal/driver/driver.go
> +func (d *Driver) updateExistingDevice(device models.Device, discDev sdkModel.DiscoveredDevice) error {
It should yes. All of this makes up the code from the earlier commits of this pr and then the device status that I added later.

2022-06-02 21:08 UTC, ChristianDarr-personal commented on internal/driver/constants.go
> +	UnreachableDesc   = "Cannot be discovered"
This isn't fully necessary, at least not in this form. I was talking to Todd about it, and he mentioned wanting a field to address this, and to let the user have some configurability, if I remember correctly. Though this might be something more appropriately addressed in 5602 - the detailed status online/offline story, but I'm not sure.

2022-06-02 22:34 UTC, ajcasagrande commented on internal/driver/driver.go
> +func (d *Driver) updateExistingDevice(device models.Device, discDev sdkModel.DiscoveredDevice) error {
I think maybe the comment about it always being logged when `both` is selected was throwing me off. i think that is no longer the case.

2022-06-02 22:42 UTC, ChristianDarr-personal commented on internal/driver/constants.go
> +	UnreachableDesc   = "Cannot be discovered"
Sounds good

2022-06-02 22:49 UTC, ChristianDarr-personal commented on internal/driver/checkstatus.go
> +		device.Protocols[OnvifProtocol][LastSeen] = time.Now().Format(time.UnixDate)
This is another instance where using the Protocol map limits the type of the value to string

2022-06-02 22:58 UTC, ajcasagrande requested changes

2022-06-02 22:58 UTC, ajcasagrande commented on cmd/res/configuration.toml
> +DiscoverySubnets = "0"
typo here? I think it should be blank by default

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +// checkStatuses loops through all discovered and tries to determine the most accurate operating state
```suggestion
// checkStatuses loops through all registered devices and tries to determine the most accurate connection state
```

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +			status = UpWithAuthDesc
this is supposed to be up with no auth or something

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	net.DialTCP(host, nil, nil) // TODO: im
use this as an example:

https://github.com/edgexfoundry/device-rfid-llrp-go/blob/0104dcba4435a7bec0bb376ad6177bfc09b37bcb/internal/driver/discover.go#L336-L343

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +			d.lc.Debugf("Time elapsed for checkStatuses: %s", time.Since(start))
need to use `%v`
```suggestion
			d.lc.Debugf("checkStatuses completed in %v", time.Since(start))
```

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +// RunUntilCancelled sets up the taskLoop and will continually run it until cancelled
```suggestion
// StartTaskLoop runs the taskLoop in the background until cancelled
```

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +		signals := make(chan os.Signal, 1) // TODO: determine if this should be 2
i double checked. 1 is the correct value.

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/driver.go
> +			errors.NewCommonEdgeX(errors.KindUnknown, "Task loop could not not start", err) // TODO: figure out error kind
should this be returned?

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	// // update entry in core metadata
remove all the commented out blocks, they aren't needed

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	if addr == "" || port == "" {
check if `OnvifProtocol` is a valid key otherwise a panic will occur

2022-06-02 22:58 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +	for _, device := range service.RunningService().Devices() { // TODO: ensure this returns the proper value
this todo isn't really needed, the device map used this same call internally

2022-06-02 23:03 UTC, ChristianDarr-personal commented on internal/driver/checkstatus.go
> +			status = UpWithAuthDesc
That has been fixed, I cleaned up a bit while you were reviewing

2022-06-02 23:25 UTC, ChristianDarr-personal commented on internal/driver/driver.go
> +	if d.config.EnableStatusCheck == 1 {
Well my thoughts were if we use it upfront while initializing, it will save us from even entering the function at all if we don't need to.

2022-06-02 23:26 UTC, ChristianDarr-personal commented on internal/driver/checkstatus.go
> +		d.lc.Debugf("Connection to %s failed when using authentication", device.Name)
I could be wrong but it doesn't look like its logged in the child function

2022-06-03 16:36 UTC, trleasher-intel commented on cmd/res/configuration.toml
> +# Maximum 300s
Having a max on the interval will ensure that users have not mistakenly configured a value that results in system behavior that is unexpected. If a particular implementation would like to increase the max value above to something above 300 seconds/5 minutes they have the source code and can make this change. While I certainly agree that some use cases may want a larger value it's unlikely that the majority of users will find it useful for the latency to approach an hour. We need to draw the line somewhere and then get feedback. Additionally, we are going have to define a default, in the toml file, and this needs to reflect a common expectation. Something more than a minute will result in numerous questions and support issues being raised.

2022-06-06 14:45 UTC, brianointel approved these changes

2022-06-06 17:34 UTC, ajcasagrande commented on cmd/res/configuration.toml
> +# Maximum 300s
@trleasher-intel sounds good. thanks for the explanation.

2022-06-06 17:40 UTC, ajcasagrande commented on internal/driver/checkstatus.go
> +		d.lc.Debugf("Connection to %s failed when using authentication", device.Name)
ok, then you should add the error as well to the log message.

2022-06-06 17:43 UTC, ajcasagrande commented
@ChristianDarr-personal edgexfoundry#75 has been merged into main, so this branch should be rebased against edgexfoundry/main. There are a few changes you can update which include the bool field.

Optionally you can also open a new PR against that repo for your rebased branch.

2022-06-06 23:23 UTC, closed without merging